### Create a new customer and extract their ID
POST http://localhost:8080/customer/create
Content-Type: application/json

{
  "name": "Peter van Proosdijk",
  "email": "pvproos@gmail.com",
  "phone": "+31645394959",
  "address": "Kerkewijk 112 Veenendaal",
  "job": "Vertegenwoordiger"
}

> {%
    // Access the JSON body of the response and get the 'id' field
    const customerId = response.body.id;

    // Set a global variable to be used in subsequent requests
    client.global.set("customerId", customerId);
%}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "vacuumcleaner",
  "quantity": 1,
  "price": 300.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "smart tv",
  "quantity": 3,
  "price": 1450.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "iphone",
  "quantity": 2,
  "price": 560.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "drill",
  "quantity": 1,
  "price": 250.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "skrew driver",
  "quantity": 6,
  "price": 12.50
}


### Create a new customer and extract their ID
POST http://localhost:8080/customer/create
Content-Type: application/json

{
  "name": "Bas Crompvoets",
  "email": "bc@gmail.com",
  "phone": "+31645694959",
  "address": "Bruglaan 12 Rhenen",
  "job": "Badmeester"
}

> {%
    // Access the JSON body of the response and get the 'id' field
    const customerId = response.body.id;

    // Set a global variable to be used in subsequent requests
    client.global.set("customerId", customerId);
%}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "skrew driver",
  "quantity": 4,
  "price": 12.50
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "hammer",
  "quantity": 2,
  "price": 15.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "photo camera",
  "quantity": 1,
  "price": 1250.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "dish wasser",
  "quantity": 1,
  "price": 850.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "chair",
  "quantity": 6,
  "price": 75.00
}

### Create a new customer and extract their ID
POST http://localhost:8080/customer/create
Content-Type: application/json

{
  "name": "Rik Sprenkels",
  "email": "rs@gmail.com",
  "phone": "+31609839959",
  "address": "Boslaan 5 Amerongen",
  "job": "Timmerman"
}

> {%
    // Access the JSON body of the response and get the 'id' field
    const customerId = response.body.id;

    // Set a global variable to be used in subsequent requests
    client.global.set("customerId", customerId);
%}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "skrew driver",
  "quantity": 6,
  "price": 12.50
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "chair",
  "quantity": 6,
  "price": 75.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "hammer",
  "quantity": 2,
  "price": 15.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "skrews m4",
  "quantity": 4,
  "price": 10.00
}

### Create an order using the extracted customer ID
POST http://localhost:8080/order/create
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "productName": "tiles",
  "quantity": 40,
  "price": 12.50
}